name: Build and Push Microservices

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch previous commit to compare changes

      - name: Get Changed Files
        id: changed-files
        run: |
          echo "🔍 Detecting changed files..."
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '^src/' | cut -d '/' -f2 | sort -u)
          echo "Changed services: $CHANGED_FILES"
          echo "CHANGED_SERVICES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Set Release Tag
        id: release-tag
        run: |
          export TAG=release_$(date +'%Y%m%d')
          echo "🆕 Release tag: $TAG"
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV

      - name: Log In to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          echo "🚀 Starting build process..."
          if [[ -z "$CHANGED_SERVICES" ]]; then
            echo "✅ No microservices changed. Skipping Docker build & push."
            exit 0
          fi

          for SERVICE in $CHANGED_SERVICES; do
            IMAGE_NAME="suriya1776/opentelementry:${SERVICE}_${RELEASE_TAG}"
            
            echo "🔹 Processing service: $SERVICE"
            echo "📦 Building Docker image: $IMAGE_NAME"
          
            docker build --progress=plain -t $IMAGE_NAME src/$SERVICE || {
              echo "❌ Build failed for $SERVICE"
              exit 1
            }
          
            echo "📤 Pushing Docker image: $IMAGE_NAME"
            docker push $IMAGE_NAME || {
              echo "❌ Push failed for $SERVICE"
              exit 1
            }
          
            echo "✅ Successfully pushed $IMAGE_NAME"
          done
        
        
