name: Testing workflow with name
run_name: Testing run name

on: [push]

jobs:
  print_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello, this is a basic print statement workflow!"
